;;;; foo.import.scm - GENERATED BY CHICKEN 4.5.0 -*- Scheme -*-

(eval '(import chicken scheme foreign foreigners))
(##sys#register-compiled-module
  'foo
  (list)
  '((hello . foo#hello)
    (g58 . foo#g58)
    (g57 . foo#g57)
    (ccount->int . foo#ccount->int)
    (int->ccount . foo#int->ccount)
    (c:goodbye . foo#c:goodbye))
  (list)
  (list))

;; END OF FILE
